server:
  port: 8761

spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8086/service-registry/eureka/
